---
abstract: 'TheSchwartz based on Moose!'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  DBI: 0
  Moose: 0.79
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TheSchwartz-Moosified
provides:
  TheSchwartz::Moosified:
    file: lib/TheSchwartz/Moosified.pm
    version: 0.06
  TheSchwartz::Moosified::Job:
    file: lib/TheSchwartz/Moosified/Job.pm
  TheSchwartz::Moosified::JobHandle:
    file: lib/TheSchwartz/Moosified/JobHandle.pm
  TheSchwartz::Moosified::Utils:
    file: lib/TheSchwartz/Moosified/Utils.pm
  TheSchwartz::Moosified::Worker:
    file: lib/TheSchwartz/Moosified/Worker.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
